inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop/rspec/focused
  - rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - config/environments/*
    - db/schema.rb
    - db/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - config/initializers/*

  TargetRubyVersion: 2.5.1

RSpec/NestedGroups:
  Max: 7

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - app/serializers/**/*
    - spec/**/*

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

RSpec/SubjectStub:
  Exclude:
    - spec/**/*

RSpec/NamedSubject:
  Exclude:
    - spec/**/*

Rails:
  Enabled: true

RSpec/Focused:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
